### ISSUE TITLE
Make status messages expire

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-webapp#2]
As we discussed, make them disappear after a short time? Or leave them but change the appearance (e.g. grey+strikethrough).

**Comment by mechawrench** [comment]
These messages will now fade after 6 seconds, live on the production site now

Let me know if this works out well in practice

**Comment by dmcomm** [comment]
That works! Maybe a little too quick. Would probably be good on the digiroms page too.

**Comment by mechawrench** [comment]
On QA the messages will go away after 60 seconds now, up from 6.  Digiroms page code sending will also remain for 60 seconds, and works with ACKs.

**Comment by dmcomm** [comment]
Great! Also make the message go away immediately if we change any of the related inputs (and stop listening for that ack code)?

I think there's something odd happening on the digiroms page when I change the input - it seems to disappear and then come back even though I haven't pressed the button.

**Comment by dmcomm** [comment]
See #10
