### ISSUE TITLE
Stop status messages moving other elements around

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-webapp#3]
In RTB there's a big space on the left of the buttons that they could go in. In Wifi Coms there isn't so much space, but it's a matter of reserving enough so that the message appearing doesn't expand it.

**Comment by mechawrench** [comment]
This has been implemented and is live on production, leaving the issue open as I may need to do more CSS work after some use.

**Comment by mechawrench** [comment]
Closing this out, I'm happy with the current state -  a UI overhaul will occur down the road, I'll touch this up then.
