### ISSUE TITLE
Buttons for "Accept Realtime Battle" should be mutually exclusive

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-webapp#4]
On the guest side, when we can start we can't retry, and vice versa.

**Comment by dmcomm** [comment]
Currently the start button isn't coming back when I put a new invite code.

**Comment by dmcomm** [comment]
Also the start button isn't disabled until after the status message fades.

**Comment by mechawrench** [comment]
These should be addressed if you can try again (on qa):

- Start button fixed to allow new invite codes, will reactivate button when the code changes
- Start button should be disabled shortly after pressing start (guest) now

**Comment by dmcomm** [comment]
Great! One more: On the guest side, if we try to reuse an invite code with a different WiFiCom Device, that should report an error.

**Comment by dmcomm** [comment]
I proposed on Discord:
* move device selection above invite code
* changing device selection clears invite code

(There still needs to be an error message if user submits the same invite code again.)

**Comment by dmcomm** [comment]
See #12
